In [1]:
import os
from pathlib import Path
# Ensure CWD is repo root so relative paths and `research.*` imports resolve.
if Path.cwd().name == "notebooks":
    os.chdir("..")

# Annotation Error Detection on the decicontas.br Dataset

This notebook applies **Annotation Error Detection (AED)** techniques to the `decicontas.br` dataset, which contains decisions from the Rio Grande do Norte State Court of Accounts (TCE/RN), manually annotated via Label Studio with entities such as `MULTA`, `OBRIGACAO`, `RECOMENDACAO`, and `RESSARCIMENTO`.

The approach is inspired by the error-detection work on the LeNER-Br dataset, but with **significant improvements**:

1. **More robust model**: we use a Transformer fine-tuned for NER (token classification) instead of only an SGDClassifier over static embeddings.
2. **Model ensemble**: we combine predictions from a linear classifier (over BERT embeddings) and a fine-tuned Transformer for greater robustness.
3. **Format adaptation**: automatic conversion of Label Studio annotations (spans) to token-level BIO format.
4. **Contextual analysis**: rich display of the detected errors with expanded context.

The core technique is **Confident Learning**, implemented by the [Cleanlab](https://github.com/cleanlab/cleanlab) library, which identifies potentially mislabeled instances based on the probabilities predicted by a classifier.

# 1. Environment Setup

In [2]:
import os
import json
import numpy as np
import pandas as pd
import torch
import warnings
warnings.filterwarnings('ignore')

os.environ["PYTORCH_MPS_HIGH_WATERMARK_RATIO"] = "0.0"

from collections import defaultdict, Counter
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, classification_report

from transformers import (
    AutoTokenizer, AutoModel, AutoModelForTokenClassification,
    TrainingArguments, Trainer, DataCollatorForTokenClassification
)
from datasets import Dataset, DatasetDict
from cleanlab.filter import find_label_issues

NUM_FOLDS_CV = 5
RANDOM_SEED = 43
EFFECTIVE_MAX_LENGTH = 512

device = torch.device('cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu')
print(f'Usando device: {device}')

Usando device: mps

# 2. Dataset Loading and Conversion

The `decicontas.br` dataset uses Label Studio annotations (spans with `start`/`end`/`text`/`labels`). We need to convert them to token-level **BIO** (Beginning-Inside-Outside) format, which is the standard for NER tasks.

We use the spaCy tokenizer (`pt_core_news_sm`) to segment the texts into tokens and align the span annotations with the resulting tokens.

In [3]:
# Mapeamento de labels (mesmo usado no projeto original)
DICT_LABELS = {
    'MULTA_FIXA': 'MULTA',
    'MULTA_PERCENTUAL': 'MULTA',
    'OBRIGACAO_MULTA': 'OBRIGACAO'
}

def translate_label(label):
    """Traduz labels compostos para suas formas simplificadas."""
    return DICT_LABELS.get(label, label)

def load_decicontas():
    """Carrega o dataset decicontas (861 docs, com filtro fewshot já aplicado).

    Usa o loader canônico research.dataset.get_decicontas_df, que exclui os 5
    documentos cujos textos integram os exemplos few-shot do prompt das LLMs.
    Os dados extras de ressarcimentos (decicontas_more_ressarcimentos.json)
    foram propositalmente removidos para alinhar a base com o resto do pipeline
    (avaliação LLM e k-fold supervisionado), todos sobre os mesmos 861 docs.
    """
    from research.dataset import get_decicontas_df
    df = get_decicontas_df()
    return df[['annotations', 'data']].copy()

def extract_spans(annotations):
    """Extrai spans anotados de uma entrada do Label Studio."""
    spans = []
    for annot in annotations:
        for result in annot.get('result', []):
            val = result.get('value', {})
            if 'start' in val and 'end' in val and 'labels' in val:
                label = translate_label(val['labels'][0])
                spans.append({
                    'start': val['start'],
                    'end': val['end'],
                    'text': val['text'],
                    'label': label
                })
    # Ordenar por posição de início
    spans.sort(key=lambda s: s['start'])
    return spans

In [4]:
def spans_to_bio_tokens(text, spans):
    """
    Converte texto + spans (Label Studio) em listas de tokens e tags BIO.
    Usa tokenização por espaços + pontuação simples para manter alinhamento com offsets.
    """
    import re
    
    # Tokenização baseada em offsets (preserva posições exatas)
    tokens = []
    token_offsets = []
    for match in re.finditer(r'\S+', text):
        tokens.append(match.group())
        token_offsets.append((match.start(), match.end()))
    
    # Atribuir BIO tags
    bio_tags = ['O'] * len(tokens)
    
    for span in spans:
        span_start = span['start']
        span_end = span['end']
        label = span['label']
        first_token = True
        
        for idx, (tok_start, tok_end) in enumerate(token_offsets):
            # Token sobrepõe com o span?
            if tok_start < span_end and tok_end > span_start:
                if first_token:
                    bio_tags[idx] = f'B-{label}'
                    first_token = False
                else:
                    bio_tags[idx] = f'I-{label}'
    
    return tokens, bio_tags

In [5]:
# Carregar dataset
# Ajuste os caminhos conforme necessário
df = load_decicontas()

print(f'Total de registros carregados: {len(df)}')

# Converter para formato BIO
sentencas = []  # Lista de listas de (token, tag)
registros_com_anotacao = 0

for idx, row in df.iterrows():
    text = row['data']['text']
    spans = extract_spans(row['annotations'])
    tokens, bio_tags = spans_to_bio_tokens(text, spans)
    
    if tokens:  # Ignorar textos vazios
        sentencas.append(list(zip(tokens, bio_tags)))
        if any(tag != 'O' for tag in bio_tags):
            registros_com_anotacao += 1

print(f'Total de sentenças/documentos convertidos: {len(sentencas)}')
print(f'Documentos com pelo menos uma entidade anotada: {registros_com_anotacao}')

Total de registros carregados: 861
Total de sentenças/documentos convertidos: 861
Documentos com pelo menos uma entidade anotada: 229

In [6]:
# Extrair todos os tokens e labels em listas planas
todos_tokens = []
todos_labels_ner = []
ids_sentenca = []

for i, sentenca in enumerate(sentencas):
    for token_text, ner_tag in sentenca:
        todos_tokens.append(token_text)
        todos_labels_ner.append(ner_tag)
        ids_sentenca.append(i)

print(f'Total de tokens: {len(todos_tokens)}')
print(f'Labels únicas: {sorted(set(todos_labels_ner))}')

# Distribuição de labels
contagem = Counter(todos_labels_ner)
print('\nDistribuição de labels:')
for label, count in contagem.most_common():
    print(f'  {label}: {count} ({100*count/len(todos_labels_ner):.2f}%)')

Total de tokens: 116844
Labels únicas: ['B-MULTA', 'B-OBRIGACAO', 'B-RECOMENDACAO', 'B-RESSARCIMENTO', 'I-MULTA', 'I-OBRIGACAO', 'I-RECOMENDACAO', 'I-RESSARCIMENTO', 'O']

Distribuição de labels:
  O: 92676 (79.32%)
  I-MULTA: 11020 (9.43%)
  I-OBRIGACAO: 7769 (6.65%)
  I-RESSARCIMENTO: 2865 (2.45%)
  I-RECOMENDACAO: 2075 (1.78%)
  B-MULTA: 202 (0.17%)
  B-OBRIGACAO: 119 (0.10%)
  B-RESSARCIMENTO: 62 (0.05%)
  B-RECOMENDACAO: 56 (0.05%)

In [7]:
# Exemplo de sentença anotada
for i, sent in enumerate(sentencas):
    if any(tag != 'O' for _, tag in sent):
        print(f'\nExemplo de sentença #{i} (primeiros 30 tokens):')
        for token, tag in sent[:30]:
            marker = '  <--' if tag != 'O' else ''
            print(f'  {token:40s} {tag}{marker}')
        if len(sent) > 30:
            print(f'  ... ({len(sent)} tokens no total)')
        break

Exemplo de sentença #67 (primeiros 30 tokens):
  Vistos,                                  O
  relatados                                O
  e                                        O
  discutidos                               O
  estes                                    O
  autos,acatando                           O
  o                                        O
  entendimento                             O
  do                                       O
  Ministério                               O
  Público                                  O
  Especial,                                O
  com                                      O
  fulcro                                   O
  nos                                      O
  fundamentos                              O
  jurídicos                                O
  dantes                                   O
  explanados,                              O
  ACORDAM                                  O
  os                                       O
  Conselheiros,                            O
  nos                                      O
  termos                                   O
  do                                       O
  voto                                     O
  proferido                                O
  pelo                                     O
  Conselheiro                              O
  Relator,                                 O
  ... (237 tokens no total)

# 3. Feature Extraction with BERTimbau

We use the `neuralmind/bert-large-portuguese-cased` model (BERTimbau Large) to extract contextual embeddings for each token. These embeddings serve as features for the linear classifier that feeds Cleanlab.

For each original token, we average the embeddings of its BERT subwords.

In [8]:
hf_model_name = 'neuralmind/bert-large-portuguese-cased'

tokenizer_hf = AutoTokenizer.from_pretrained(hf_model_name)
model_hf = AutoModel.from_pretrained(hf_model_name)
model_hf.to(device)
model_hf.eval()

print(f'Modelo carregado: {hf_model_name}')
print(f'Dimensão dos embeddings: {model_hf.config.hidden_size}')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: neuralmind/bert-large-portuguese-cased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Modelo carregado: neuralmind/bert-large-portuguese-cased
Dimensão dos embeddings: 1024

In [9]:
from tqdm import tqdm

features_tokens = []

for i_sent, dados_sentenca in enumerate(tqdm(sentencas, desc='Extraindo embeddings')):
    textos_sentenca = [tok for tok, _ in dados_sentenca]

    if not textos_sentenca:
        continue

    inputs = tokenizer_hf(
        textos_sentenca,
        is_split_into_words=True,
        return_tensors='pt',
        padding='longest',
        truncation=True,
        max_length=EFFECTIVE_MAX_LENGTH
    ).to(device)

    word_ids = inputs.word_ids()
    with torch.no_grad():
        outputs = model_hf(**inputs)
        last_hidden_state = outputs.last_hidden_state

    token_subword_embeddings = [[] for _ in range(len(textos_sentenca))]
    for subword_idx, original_word_idx in enumerate(word_ids):
        if original_word_idx is not None:
            embedding = last_hidden_state[0, subword_idx, :]
            token_subword_embeddings[original_word_idx].append(embedding)

    for original_token_idx in range(len(textos_sentenca)):
        if token_subword_embeddings[original_token_idx]:
            stacked = torch.stack(token_subword_embeddings[original_token_idx])
            mean_emb = torch.mean(stacked, dim=0)
            features_tokens.append(mean_emb.cpu().numpy())
        else:
            features_tokens.append(np.zeros(model_hf.config.hidden_size))

features_tokens = np.array(features_tokens)
print(f'Formato da matriz de features: {features_tokens.shape}')

Extraindo embeddings:   0%|          | 0/861 [00:00<?, ?it/s]

Extraindo embeddings:   0%|          | 1/861 [00:00<02:41,  5.34it/s]

Extraindo embeddings:   0%|          | 4/861 [00:00<01:01, 13.87it/s]

Extraindo embeddings:   1%|          | 7/861 [00:00<00:51, 16.53it/s]

Extraindo embeddings:   1%|          | 9/861 [00:00<00:48, 17.39it/s]

Extraindo embeddings:   1%|▏         | 12/861 [00:00<00:44, 19.20it/s]

Extraindo embeddings:   2%|▏         | 15/861 [00:00<00:40, 20.79it/s]

Extraindo embeddings:   2%|▏         | 18/861 [00:00<00:40, 20.75it/s]

Extraindo embeddings:   2%|▏         | 21/861 [00:01<00:39, 21.08it/s]

Extraindo embeddings:   3%|▎         | 24/861 [00:01<00:37, 22.09it/s]

Extraindo embeddings:   3%|▎         | 27/861 [00:01<00:37, 22.20it/s]

Extraindo embeddings:   3%|▎         | 30/861 [00:01<00:39, 20.91it/s]

Extraindo embeddings:   4%|▍         | 33/861 [00:01<00:38, 21.74it/s]

Extraindo embeddings:   4%|▍         | 36/861 [00:01<00:35, 23.32it/s]

Extraindo embeddings:   5%|▍         | 39/861 [00:01<00:37, 22.18it/s]

Extraindo embeddings:   5%|▍         | 42/861 [00:02<00:38, 21.55it/s]

Extraindo embeddings:   5%|▌         | 45/861 [00:02<00:36, 22.14it/s]

Extraindo embeddings:   6%|▌         | 48/861 [00:02<00:37, 21.58it/s]

Extraindo embeddings:   6%|▌         | 51/861 [00:02<00:36, 22.30it/s]

Extraindo embeddings:   6%|▋         | 54/861 [00:02<00:35, 22.51it/s]

Extraindo embeddings:   7%|▋         | 57/861 [00:02<00:36, 21.74it/s]

Extraindo embeddings:   7%|▋         | 60/861 [00:02<00:34, 23.06it/s]

Extraindo embeddings:   7%|▋         | 63/861 [00:03<00:48, 16.32it/s]

Extraindo embeddings:   8%|▊         | 65/861 [00:03<00:52, 15.14it/s]

Extraindo embeddings:   8%|▊         | 67/861 [00:03<00:50, 15.68it/s]

Extraindo embeddings:   8%|▊         | 69/861 [00:03<01:07, 11.70it/s]

Extraindo embeddings:   8%|▊         | 71/861 [00:03<01:06, 11.88it/s]

Extraindo embeddings:   8%|▊         | 73/861 [00:04<01:04, 12.27it/s]

Extraindo embeddings:   9%|▊         | 75/861 [00:04<01:11, 11.02it/s]

Extraindo embeddings:   9%|▉         | 77/861 [00:04<01:19,  9.86it/s]

Extraindo embeddings:   9%|▉         | 79/861 [00:04<01:13, 10.59it/s]

Extraindo embeddings:   9%|▉         | 81/861 [00:04<01:07, 11.53it/s]

Extraindo embeddings:  10%|▉         | 83/861 [00:05<01:14, 10.51it/s]

Extraindo embeddings:  10%|▉         | 85/861 [00:05<01:33,  8.27it/s]

Extraindo embeddings:  10%|█         | 88/861 [00:05<01:19,  9.69it/s]

Extraindo embeddings:  10%|█         | 90/861 [00:05<01:32,  8.31it/s]

Extraindo embeddings:  11%|█         | 92/861 [00:06<01:23,  9.21it/s]

Extraindo embeddings:  11%|█         | 94/861 [00:06<01:28,  8.63it/s]

Extraindo embeddings:  11%|█         | 95/861 [00:06<01:28,  8.69it/s]

Extraindo embeddings:  11%|█▏        | 97/861 [00:06<01:18,  9.70it/s]

Extraindo embeddings:  11%|█▏        | 99/861 [00:06<01:11, 10.65it/s]

Extraindo embeddings:  12%|█▏        | 101/861 [00:06<01:06, 11.37it/s]

Extraindo embeddings:  12%|█▏        | 103/861 [00:07<01:12, 10.47it/s]

Extraindo embeddings:  12%|█▏        | 105/861 [00:07<01:20,  9.41it/s]

Extraindo embeddings:  12%|█▏        | 107/861 [00:07<01:18,  9.61it/s]

Extraindo embeddings:  13%|█▎        | 109/861 [00:07<01:13, 10.29it/s]

Extraindo embeddings:  13%|█▎        | 112/861 [00:07<00:58, 12.81it/s]

Extraindo embeddings:  13%|█▎        | 114/861 [00:08<01:10, 10.53it/s]

Extraindo embeddings:  13%|█▎        | 116/861 [00:08<01:21,  9.18it/s]

Extraindo embeddings:  14%|█▎        | 118/861 [00:08<01:11, 10.35it/s]

Extraindo embeddings:  14%|█▍        | 120/861 [00:08<01:22,  8.96it/s]

Extraindo embeddings:  14%|█▍        | 122/861 [00:09<01:24,  8.76it/s]

Extraindo embeddings:  14%|█▍        | 124/861 [00:09<01:22,  8.97it/s]

Extraindo embeddings:  15%|█▍        | 125/861 [00:09<01:27,  8.37it/s]

Extraindo embeddings:  15%|█▍        | 127/861 [00:09<01:11, 10.20it/s]

Extraindo embeddings:  15%|█▍        | 129/861 [00:09<01:06, 11.08it/s]

Extraindo embeddings:  15%|█▌        | 131/861 [00:09<00:59, 12.20it/s]

Extraindo embeddings:  15%|█▌        | 133/861 [00:10<01:08, 10.70it/s]

Extraindo embeddings:  16%|█▌        | 135/861 [00:10<01:05, 11.03it/s]

Extraindo embeddings:  16%|█▌        | 137/861 [00:10<01:09, 10.45it/s]

Extraindo embeddings:  16%|█▌        | 139/861 [00:10<01:02, 11.47it/s]

Extraindo embeddings:  16%|█▋        | 141/861 [00:10<01:07, 10.74it/s]

Extraindo embeddings:  17%|█▋        | 143/861 [00:11<01:15,  9.57it/s]

Extraindo embeddings:  17%|█▋        | 145/861 [00:11<01:07, 10.63it/s]

Extraindo embeddings:  17%|█▋        | 147/861 [00:11<01:10, 10.18it/s]

Extraindo embeddings:  17%|█▋        | 149/861 [00:11<01:23,  8.56it/s]

Extraindo embeddings:  18%|█▊        | 151/861 [00:12<01:20,  8.81it/s]

Extraindo embeddings:  18%|█▊        | 152/861 [00:12<01:26,  8.17it/s]

Extraindo embeddings:  18%|█▊        | 153/861 [00:12<01:29,  7.87it/s]

Extraindo embeddings:  18%|█▊        | 154/861 [00:12<01:32,  7.61it/s]

Extraindo embeddings:  18%|█▊        | 156/861 [00:12<01:17,  9.05it/s]

Extraindo embeddings:  18%|█▊        | 158/861 [00:12<01:05, 10.72it/s]

Extraindo embeddings:  19%|█▊        | 160/861 [00:13<01:14,  9.46it/s]

Extraindo embeddings:  19%|█▉        | 162/861 [00:13<01:10,  9.96it/s]

Extraindo embeddings:  19%|█▉        | 164/861 [00:13<01:09,  9.96it/s]

Extraindo embeddings:  19%|█▉        | 166/861 [00:13<01:06, 10.37it/s]

Extraindo embeddings:  20%|█▉        | 168/861 [00:13<01:03, 10.86it/s]

Extraindo embeddings:  20%|█▉        | 170/861 [00:14<01:11,  9.68it/s]

Extraindo embeddings:  20%|█▉        | 172/861 [00:14<01:01, 11.28it/s]

Extraindo embeddings:  20%|██        | 174/861 [00:14<01:00, 11.37it/s]

Extraindo embeddings:  20%|██        | 176/861 [00:14<01:08,  9.93it/s]

Extraindo embeddings:  21%|██        | 178/861 [00:14<01:14,  9.17it/s]

Extraindo embeddings:  21%|██        | 179/861 [00:14<01:18,  8.65it/s]

Extraindo embeddings:  21%|██        | 180/861 [00:15<01:22,  8.23it/s]

Extraindo embeddings:  21%|██        | 181/861 [00:15<01:26,  7.88it/s]

Extraindo embeddings:  21%|██        | 182/861 [00:15<01:29,  7.61it/s]

Extraindo embeddings:  21%|██▏       | 183/861 [00:15<01:31,  7.40it/s]

Extraindo embeddings:  21%|██▏       | 184/861 [00:15<01:33,  7.26it/s]

Extraindo embeddings:  21%|██▏       | 185/861 [00:15<01:34,  7.16it/s]

Extraindo embeddings:  22%|██▏       | 186/861 [00:16<01:35,  7.08it/s]

Extraindo embeddings:  22%|██▏       | 187/861 [00:16<01:35,  7.02it/s]

Extraindo embeddings:  22%|██▏       | 188/861 [00:16<01:36,  6.99it/s]

Extraindo embeddings:  22%|██▏       | 189/861 [00:16<01:35,  7.02it/s]

Extraindo embeddings:  22%|██▏       | 190/861 [00:16<01:27,  7.65it/s]

Extraindo embeddings:  22%|██▏       | 192/861 [00:16<01:05, 10.16it/s]

Extraindo embeddings:  23%|██▎       | 194/861 [00:16<00:58, 11.47it/s]

Extraindo embeddings:  23%|██▎       | 196/861 [00:16<00:55, 11.89it/s]

Extraindo embeddings:  23%|██▎       | 198/861 [00:17<00:55, 11.96it/s]

Extraindo embeddings:  23%|██▎       | 200/861 [00:17<00:48, 13.56it/s]

Extraindo embeddings:  23%|██▎       | 202/861 [00:17<00:49, 13.28it/s]

Extraindo embeddings:  24%|██▎       | 204/861 [00:17<01:05,  9.95it/s]

Extraindo embeddings:  24%|██▍       | 206/861 [00:17<00:57, 11.47it/s]

Extraindo embeddings:  24%|██▍       | 208/861 [00:17<00:54, 11.96it/s]

Extraindo embeddings:  24%|██▍       | 210/861 [00:18<00:50, 12.79it/s]

Extraindo embeddings:  25%|██▍       | 213/861 [00:18<00:43, 14.80it/s]

Extraindo embeddings:  25%|██▍       | 215/861 [00:18<00:57, 11.23it/s]

Extraindo embeddings:  25%|██▌       | 217/861 [00:18<01:08,  9.44it/s]

Extraindo embeddings:  25%|██▌       | 219/861 [00:18<01:01, 10.37it/s]

Extraindo embeddings:  26%|██▌       | 221/861 [00:19<00:58, 10.91it/s]

Extraindo embeddings:  26%|██▌       | 223/861 [00:19<00:53, 11.89it/s]

Extraindo embeddings:  26%|██▌       | 225/861 [00:19<01:03, 10.03it/s]

Extraindo embeddings:  26%|██▋       | 227/861 [00:19<01:00, 10.40it/s]

Extraindo embeddings:  27%|██▋       | 229/861 [00:19<00:55, 11.39it/s]

Extraindo embeddings:  27%|██▋       | 231/861 [00:20<01:12,  8.64it/s]

Extraindo embeddings:  27%|██▋       | 233/861 [00:20<01:08,  9.18it/s]

Extraindo embeddings:  27%|██▋       | 235/861 [00:20<00:57, 10.93it/s]

Extraindo embeddings:  28%|██▊       | 237/861 [00:20<00:54, 11.37it/s]

Extraindo embeddings:  28%|██▊       | 239/861 [00:20<00:58, 10.55it/s]

Extraindo embeddings:  28%|██▊       | 241/861 [00:21<00:54, 11.37it/s]

Extraindo embeddings:  28%|██▊       | 243/861 [00:21<00:55, 11.22it/s]

Extraindo embeddings:  28%|██▊       | 245/861 [00:21<00:51, 11.92it/s]

Extraindo embeddings:  29%|██▊       | 247/861 [00:21<00:52, 11.59it/s]

Extraindo embeddings:  29%|██▉       | 249/861 [00:21<00:49, 12.31it/s]

Extraindo embeddings:  29%|██▉       | 251/861 [00:21<00:55, 10.92it/s]

Extraindo embeddings:  29%|██▉       | 253/861 [00:22<00:57, 10.57it/s]

Extraindo embeddings:  30%|██▉       | 255/861 [00:22<00:57, 10.53it/s]

Extraindo embeddings:  30%|██▉       | 257/861 [00:22<00:56, 10.76it/s]

Extraindo embeddings:  30%|███       | 259/861 [00:22<01:00,  9.91it/s]

Extraindo embeddings:  30%|███       | 261/861 [00:22<00:56, 10.65it/s]

Extraindo embeddings:  31%|███       | 263/861 [00:23<00:54, 10.95it/s]

Extraindo embeddings:  31%|███       | 265/861 [00:23<00:50, 11.80it/s]

Extraindo embeddings:  31%|███       | 267/861 [00:23<00:51, 11.61it/s]

Extraindo embeddings:  31%|███       | 269/861 [00:23<00:53, 11.06it/s]

Extraindo embeddings:  31%|███▏      | 271/861 [00:23<00:46, 12.75it/s]

Extraindo embeddings:  32%|███▏      | 273/861 [00:23<00:42, 13.91it/s]

Extraindo embeddings:  32%|███▏      | 275/861 [00:23<00:42, 13.69it/s]

Extraindo embeddings:  32%|███▏      | 277/861 [00:24<00:43, 13.50it/s]

Extraindo embeddings:  32%|███▏      | 279/861 [00:24<00:45, 12.92it/s]

Extraindo embeddings:  33%|███▎      | 281/861 [00:24<00:45, 12.86it/s]

Extraindo embeddings:  33%|███▎      | 284/861 [00:24<00:38, 15.04it/s]

Extraindo embeddings:  33%|███▎      | 286/861 [00:24<00:39, 14.44it/s]

Extraindo embeddings:  33%|███▎      | 288/861 [00:24<00:40, 14.28it/s]

Extraindo embeddings:  34%|███▎      | 290/861 [00:24<00:37, 15.36it/s]

Extraindo embeddings:  34%|███▍      | 293/861 [00:25<00:33, 17.15it/s]

Extraindo embeddings:  34%|███▍      | 295/861 [00:25<00:40, 14.02it/s]

Extraindo embeddings:  34%|███▍      | 297/861 [00:25<00:43, 12.98it/s]

Extraindo embeddings:  35%|███▍      | 299/861 [00:25<00:48, 11.51it/s]

Extraindo embeddings:  35%|███▍      | 301/861 [00:25<00:45, 12.32it/s]

Extraindo embeddings:  35%|███▌      | 303/861 [00:25<00:41, 13.37it/s]

Extraindo embeddings:  35%|███▌      | 305/861 [00:26<00:41, 13.28it/s]

Extraindo embeddings:  36%|███▌      | 307/861 [00:26<00:42, 13.17it/s]

Extraindo embeddings:  36%|███▌      | 309/861 [00:26<00:40, 13.76it/s]

Extraindo embeddings:  36%|███▌      | 311/861 [00:26<00:36, 15.02it/s]

Extraindo embeddings:  36%|███▋      | 313/861 [00:26<00:34, 15.81it/s]

Extraindo embeddings:  37%|███▋      | 315/861 [00:26<00:35, 15.55it/s]

Extraindo embeddings:  37%|███▋      | 317/861 [00:27<00:47, 11.45it/s]

Extraindo embeddings:  37%|███▋      | 319/861 [00:27<00:51, 10.58it/s]

Extraindo embeddings:  37%|███▋      | 321/861 [00:27<00:54,  9.88it/s]

Extraindo embeddings:  38%|███▊      | 323/861 [00:27<01:01,  8.69it/s]

Extraindo embeddings:  38%|███▊      | 324/861 [00:27<01:05,  8.23it/s]

Extraindo embeddings:  38%|███▊      | 325/861 [00:28<01:08,  7.85it/s]

Extraindo embeddings:  38%|███▊      | 327/861 [00:28<00:56,  9.46it/s]

Extraindo embeddings:  38%|███▊      | 329/861 [00:28<00:50, 10.56it/s]

Extraindo embeddings:  38%|███▊      | 331/861 [00:28<00:48, 10.83it/s]

Extraindo embeddings:  39%|███▊      | 333/861 [00:28<00:50, 10.47it/s]

Extraindo embeddings:  39%|███▉      | 335/861 [00:28<00:51, 10.17it/s]

Extraindo embeddings:  39%|███▉      | 337/861 [00:29<00:56,  9.24it/s]

Extraindo embeddings:  39%|███▉      | 338/861 [00:29<01:03,  8.26it/s]

Extraindo embeddings:  39%|███▉      | 340/861 [00:29<01:03,  8.16it/s]

Extraindo embeddings:  40%|███▉      | 341/861 [00:29<01:06,  7.86it/s]

Extraindo embeddings:  40%|███▉      | 343/861 [00:29<00:55,  9.37it/s]

Extraindo embeddings:  40%|████      | 345/861 [00:30<00:54,  9.47it/s]

Extraindo embeddings:  40%|████      | 346/861 [00:30<00:58,  8.81it/s]

Extraindo embeddings:  40%|████      | 348/861 [00:30<00:52,  9.70it/s]

Extraindo embeddings:  41%|████      | 350/861 [00:30<00:50, 10.18it/s]

Extraindo embeddings:  41%|████      | 352/861 [00:30<00:48, 10.54it/s]

Extraindo embeddings:  41%|████      | 354/861 [00:30<00:44, 11.45it/s]

Extraindo embeddings:  41%|████▏     | 356/861 [00:31<00:43, 11.50it/s]

Extraindo embeddings:  42%|████▏     | 358/861 [00:31<00:38, 13.17it/s]

Extraindo embeddings:  42%|████▏     | 360/861 [00:31<00:41, 12.17it/s]

Extraindo embeddings:  42%|████▏     | 362/861 [00:31<00:37, 13.28it/s]

Extraindo embeddings:  42%|████▏     | 365/861 [00:31<00:31, 15.64it/s]

Extraindo embeddings:  43%|████▎     | 367/861 [00:31<00:31, 15.85it/s]

Extraindo embeddings:  43%|████▎     | 370/861 [00:31<00:27, 18.11it/s]

Extraindo embeddings:  43%|████▎     | 372/861 [00:32<00:27, 18.06it/s]

Extraindo embeddings:  43%|████▎     | 374/861 [00:32<00:28, 17.22it/s]

Extraindo embeddings:  44%|████▎     | 376/861 [00:32<00:28, 17.13it/s]

Extraindo embeddings:  44%|████▍     | 378/861 [00:32<00:27, 17.40it/s]

Extraindo embeddings:  44%|████▍     | 381/861 [00:32<00:25, 18.70it/s]

Extraindo embeddings:  45%|████▍     | 384/861 [00:32<00:24, 19.46it/s]

Extraindo embeddings:  45%|████▍     | 386/861 [00:32<00:24, 19.32it/s]

Extraindo embeddings:  45%|████▌     | 389/861 [00:32<00:24, 19.03it/s]

Extraindo embeddings:  45%|████▌     | 391/861 [00:33<00:25, 18.74it/s]

Extraindo embeddings:  46%|████▌     | 394/861 [00:33<00:23, 19.79it/s]

Extraindo embeddings:  46%|████▌     | 396/861 [00:33<00:24, 19.11it/s]

Extraindo embeddings:  46%|████▌     | 398/861 [00:33<00:29, 15.71it/s]

Extraindo embeddings:  46%|████▋     | 400/861 [00:33<00:34, 13.19it/s]

Extraindo embeddings:  47%|████▋     | 402/861 [00:33<00:32, 14.21it/s]

Extraindo embeddings:  47%|████▋     | 404/861 [00:33<00:31, 14.45it/s]

Extraindo embeddings:  47%|████▋     | 407/861 [00:34<00:27, 16.70it/s]

Extraindo embeddings:  48%|████▊     | 409/861 [00:34<00:34, 13.18it/s]

Extraindo embeddings:  48%|████▊     | 411/861 [00:34<00:32, 13.98it/s]

Extraindo embeddings:  48%|████▊     | 413/861 [00:34<00:31, 14.12it/s]

Extraindo embeddings:  48%|████▊     | 415/861 [00:34<00:38, 11.66it/s]

Extraindo embeddings:  48%|████▊     | 417/861 [00:35<00:39, 11.16it/s]

Extraindo embeddings:  49%|████▊     | 419/861 [00:35<00:35, 12.55it/s]

Extraindo embeddings:  49%|████▉     | 421/861 [00:35<00:32, 13.53it/s]

Extraindo embeddings:  49%|████▉     | 424/861 [00:35<00:27, 15.76it/s]

Extraindo embeddings:  49%|████▉     | 426/861 [00:35<00:29, 14.84it/s]

Extraindo embeddings:  50%|████▉     | 428/861 [00:35<00:27, 15.82it/s]

Extraindo embeddings:  50%|████▉     | 430/861 [00:35<00:27, 15.66it/s]

Extraindo embeddings:  50%|█████     | 432/861 [00:36<00:38, 11.17it/s]

Extraindo embeddings:  50%|█████     | 434/861 [00:36<00:34, 12.21it/s]

Extraindo embeddings:  51%|█████     | 437/861 [00:36<00:29, 14.17it/s]

Extraindo embeddings:  51%|█████     | 439/861 [00:36<00:29, 14.35it/s]

Extraindo embeddings:  51%|█████     | 441/861 [00:36<00:29, 14.28it/s]

Extraindo embeddings:  52%|█████▏    | 444/861 [00:36<00:25, 16.66it/s]

Extraindo embeddings:  52%|█████▏    | 446/861 [00:36<00:25, 16.55it/s]

Extraindo embeddings:  52%|█████▏    | 448/861 [00:37<00:25, 16.00it/s]

Extraindo embeddings:  52%|█████▏    | 450/861 [00:37<00:28, 14.51it/s]

Extraindo embeddings:  52%|█████▏    | 452/861 [00:37<00:26, 15.62it/s]

Extraindo embeddings:  53%|█████▎    | 454/861 [00:37<00:24, 16.58it/s]

Extraindo embeddings:  53%|█████▎    | 456/861 [00:37<00:24, 16.79it/s]

Extraindo embeddings:  53%|█████▎    | 458/861 [00:37<00:24, 16.59it/s]

Extraindo embeddings:  53%|█████▎    | 460/861 [00:37<00:24, 16.44it/s]

Extraindo embeddings:  54%|█████▎    | 462/861 [00:37<00:23, 17.15it/s]

Extraindo embeddings:  54%|█████▍    | 464/861 [00:38<00:23, 16.99it/s]

Extraindo embeddings:  54%|█████▍    | 466/861 [00:38<00:22, 17.74it/s]

Extraindo embeddings:  54%|█████▍    | 469/861 [00:38<00:21, 18.62it/s]

Extraindo embeddings:  55%|█████▍    | 472/861 [00:38<00:20, 18.58it/s]

Extraindo embeddings:  55%|█████▌    | 475/861 [00:38<00:18, 20.61it/s]

Extraindo embeddings:  56%|█████▌    | 478/861 [00:38<00:18, 20.91it/s]

Extraindo embeddings:  56%|█████▌    | 481/861 [00:38<00:18, 20.57it/s]

Extraindo embeddings:  56%|█████▌    | 484/861 [00:39<00:22, 17.04it/s]

Extraindo embeddings:  56%|█████▋    | 486/861 [00:39<00:22, 16.68it/s]

Extraindo embeddings:  57%|█████▋    | 489/861 [00:39<00:21, 17.57it/s]

Extraindo embeddings:  57%|█████▋    | 491/861 [00:39<00:22, 16.11it/s]

Extraindo embeddings:  57%|█████▋    | 493/861 [00:39<00:23, 15.72it/s]

Extraindo embeddings:  58%|█████▊    | 496/861 [00:39<00:26, 13.58it/s]

Extraindo embeddings:  58%|█████▊    | 498/861 [00:40<00:26, 13.67it/s]

Extraindo embeddings:  58%|█████▊    | 500/861 [00:40<00:27, 13.04it/s]

Extraindo embeddings:  58%|█████▊    | 502/861 [00:40<00:27, 13.11it/s]

Extraindo embeddings:  59%|█████▊    | 504/861 [00:40<00:24, 14.31it/s]

Extraindo embeddings:  59%|█████▉    | 506/861 [00:40<00:24, 14.45it/s]

Extraindo embeddings:  59%|█████▉    | 508/861 [00:40<00:28, 12.49it/s]

Extraindo embeddings:  59%|█████▉    | 511/861 [00:41<00:23, 14.82it/s]

Extraindo embeddings:  60%|█████▉    | 513/861 [00:41<00:22, 15.50it/s]

Extraindo embeddings:  60%|█████▉    | 516/861 [00:41<00:22, 15.10it/s]

Extraindo embeddings:  60%|██████    | 518/861 [00:41<00:24, 14.09it/s]

Extraindo embeddings:  60%|██████    | 520/861 [00:41<00:22, 15.01it/s]

Extraindo embeddings:  61%|██████    | 522/861 [00:41<00:21, 15.96it/s]

Extraindo embeddings:  61%|██████    | 524/861 [00:42<00:30, 10.97it/s]

Extraindo embeddings:  61%|██████    | 526/861 [00:42<00:32, 10.47it/s]

Extraindo embeddings:  61%|██████▏   | 528/861 [00:42<00:33,  9.82it/s]

Extraindo embeddings:  62%|██████▏   | 530/861 [00:42<00:28, 11.43it/s]

Extraindo embeddings:  62%|██████▏   | 532/861 [00:42<00:39,  8.38it/s]

Extraindo embeddings:  62%|██████▏   | 534/861 [00:43<00:33,  9.77it/s]

Extraindo embeddings:  62%|██████▏   | 536/861 [00:43<00:30, 10.52it/s]

Extraindo embeddings:  62%|██████▏   | 538/861 [00:43<00:30, 10.68it/s]

Extraindo embeddings:  63%|██████▎   | 540/861 [00:43<00:27, 11.76it/s]

Extraindo embeddings:  63%|██████▎   | 543/861 [00:43<00:21, 15.05it/s]

Extraindo embeddings:  63%|██████▎   | 545/861 [00:43<00:24, 12.75it/s]

Extraindo embeddings:  64%|██████▎   | 548/861 [00:44<00:20, 15.37it/s]

Extraindo embeddings:  64%|██████▍   | 550/861 [00:44<00:19, 16.32it/s]

Extraindo embeddings:  64%|██████▍   | 552/861 [00:44<00:18, 16.75it/s]

Extraindo embeddings:  64%|██████▍   | 555/861 [00:44<00:16, 19.08it/s]

Extraindo embeddings:  65%|██████▍   | 558/861 [00:44<00:19, 15.22it/s]

Extraindo embeddings:  65%|██████▌   | 560/861 [00:44<00:19, 15.07it/s]

Extraindo embeddings:  65%|██████▌   | 562/861 [00:44<00:21, 13.85it/s]

Extraindo embeddings:  66%|██████▌   | 564/861 [00:45<00:20, 14.84it/s]

Extraindo embeddings:  66%|██████▌   | 566/861 [00:45<00:18, 15.54it/s]

Extraindo embeddings:  66%|██████▌   | 568/861 [00:45<00:21, 13.62it/s]

Extraindo embeddings:  66%|██████▋   | 571/861 [00:45<00:18, 15.95it/s]

Extraindo embeddings:  67%|██████▋   | 573/861 [00:45<00:17, 16.29it/s]

Extraindo embeddings:  67%|██████▋   | 576/861 [00:45<00:16, 16.88it/s]

Extraindo embeddings:  67%|██████▋   | 578/861 [00:46<00:21, 13.29it/s]

Extraindo embeddings:  67%|██████▋   | 580/861 [00:46<00:19, 14.38it/s]

Extraindo embeddings:  68%|██████▊   | 582/861 [00:46<00:18, 14.69it/s]

Extraindo embeddings:  68%|██████▊   | 584/861 [00:46<00:20, 13.71it/s]

Extraindo embeddings:  68%|██████▊   | 586/861 [00:46<00:18, 14.65it/s]

Extraindo embeddings:  68%|██████▊   | 588/861 [00:46<00:19, 14.08it/s]

Extraindo embeddings:  69%|██████▊   | 590/861 [00:46<00:18, 14.78it/s]

Extraindo embeddings:  69%|██████▉   | 592/861 [00:47<00:21, 12.71it/s]

Extraindo embeddings:  69%|██████▉   | 594/861 [00:47<00:24, 10.91it/s]

Extraindo embeddings:  69%|██████▉   | 596/861 [00:47<00:26,  9.98it/s]

Extraindo embeddings:  70%|██████▉   | 599/861 [00:47<00:22, 11.81it/s]

Extraindo embeddings:  70%|██████▉   | 602/861 [00:47<00:18, 14.34it/s]

Extraindo embeddings:  70%|███████   | 604/861 [00:48<00:18, 13.81it/s]

Extraindo embeddings:  70%|███████   | 607/861 [00:48<00:16, 15.82it/s]

Extraindo embeddings:  71%|███████   | 609/861 [00:48<00:19, 13.14it/s]

Extraindo embeddings:  71%|███████   | 611/861 [00:48<00:22, 11.29it/s]

Extraindo embeddings:  71%|███████   | 613/861 [00:48<00:26,  9.23it/s]

Extraindo embeddings:  71%|███████▏  | 615/861 [00:49<00:30,  8.08it/s]

Extraindo embeddings:  72%|███████▏  | 617/861 [00:49<00:28,  8.65it/s]

Extraindo embeddings:  72%|███████▏  | 619/861 [00:49<00:28,  8.51it/s]

Extraindo embeddings:  72%|███████▏  | 620/861 [00:49<00:27,  8.73it/s]

Extraindo embeddings:  72%|███████▏  | 621/861 [00:49<00:28,  8.33it/s]

Extraindo embeddings:  72%|███████▏  | 623/861 [00:50<00:23, 10.27it/s]

Extraindo embeddings:  73%|███████▎  | 625/861 [00:50<00:23,  9.94it/s]

Extraindo embeddings:  73%|███████▎  | 627/861 [00:50<00:21, 10.87it/s]

Extraindo embeddings:  73%|███████▎  | 629/861 [00:50<00:22, 10.34it/s]

Extraindo embeddings:  73%|███████▎  | 631/861 [00:50<00:24,  9.27it/s]

Extraindo embeddings:  73%|███████▎  | 632/861 [00:51<00:25,  9.14it/s]

Extraindo embeddings:  74%|███████▎  | 634/861 [00:51<00:21, 10.63it/s]

Extraindo embeddings:  74%|███████▍  | 636/861 [00:51<00:24,  9.08it/s]

Extraindo embeddings:  74%|███████▍  | 638/861 [00:51<00:21, 10.43it/s]

Extraindo embeddings:  74%|███████▍  | 640/861 [00:51<00:22,  9.67it/s]

Extraindo embeddings:  75%|███████▍  | 643/861 [00:51<00:17, 12.29it/s]

Extraindo embeddings:  75%|███████▌  | 646/861 [00:52<00:14, 14.68it/s]

Extraindo embeddings:  75%|███████▌  | 648/861 [00:52<00:18, 11.79it/s]

Extraindo embeddings:  75%|███████▌  | 650/861 [00:52<00:16, 12.99it/s]

Extraindo embeddings:  76%|███████▌  | 652/861 [00:52<00:16, 12.53it/s]

Extraindo embeddings:  76%|███████▌  | 655/861 [00:52<00:13, 15.03it/s]

Extraindo embeddings:  76%|███████▋  | 657/861 [00:52<00:12, 15.83it/s]

Extraindo embeddings:  77%|███████▋  | 660/861 [00:52<00:11, 18.03it/s]

Extraindo embeddings:  77%|███████▋  | 663/861 [00:53<00:10, 19.32it/s]

Extraindo embeddings:  77%|███████▋  | 666/861 [00:53<00:12, 15.04it/s]

Extraindo embeddings:  78%|███████▊  | 669/861 [00:53<00:11, 16.50it/s]

Extraindo embeddings:  78%|███████▊  | 671/861 [00:53<00:14, 13.17it/s]

Extraindo embeddings:  78%|███████▊  | 673/861 [00:54<00:15, 12.00it/s]

Extraindo embeddings:  78%|███████▊  | 675/861 [00:54<00:14, 12.46it/s]

Extraindo embeddings:  79%|███████▊  | 677/861 [00:54<00:15, 11.90it/s]

Extraindo embeddings:  79%|███████▉  | 680/861 [00:54<00:12, 14.37it/s]

Extraindo embeddings:  79%|███████▉  | 682/861 [00:54<00:12, 14.78it/s]

Extraindo embeddings:  80%|███████▉  | 685/861 [00:54<00:10, 16.74it/s]

Extraindo embeddings:  80%|███████▉  | 687/861 [00:54<00:12, 14.39it/s]

Extraindo embeddings:  80%|████████  | 689/861 [00:55<00:11, 14.55it/s]

Extraindo embeddings:  80%|████████  | 691/861 [00:55<00:11, 14.58it/s]

Extraindo embeddings:  80%|████████  | 693/861 [00:55<00:12, 13.56it/s]

Extraindo embeddings:  81%|████████  | 695/861 [00:55<00:12, 13.49it/s]

Extraindo embeddings:  81%|████████  | 697/861 [00:55<00:11, 14.16it/s]

Extraindo embeddings:  81%|████████  | 699/861 [00:55<00:10, 15.30it/s]

Extraindo embeddings:  81%|████████▏ | 701/861 [00:55<00:11, 13.56it/s]

Extraindo embeddings:  82%|████████▏ | 703/861 [00:56<00:12, 12.59it/s]

Extraindo embeddings:  82%|████████▏ | 705/861 [00:56<00:12, 12.86it/s]

Extraindo embeddings:  82%|████████▏ | 708/861 [00:56<00:10, 14.18it/s]

Extraindo embeddings:  83%|████████▎ | 711/861 [00:56<00:11, 13.03it/s]

Extraindo embeddings:  83%|████████▎ | 714/861 [00:56<00:10, 14.53it/s]

Extraindo embeddings:  83%|████████▎ | 716/861 [00:57<00:10, 13.79it/s]

Extraindo embeddings:  83%|████████▎ | 718/861 [00:57<00:13, 10.59it/s]

Extraindo embeddings:  84%|████████▎ | 720/861 [00:57<00:11, 12.07it/s]

Extraindo embeddings:  84%|████████▍ | 722/861 [00:57<00:11, 12.42it/s]

Extraindo embeddings:  84%|████████▍ | 725/861 [00:57<00:09, 14.55it/s]

Extraindo embeddings:  84%|████████▍ | 727/861 [00:58<00:11, 11.78it/s]

Extraindo embeddings:  85%|████████▍ | 729/861 [00:58<00:11, 11.32it/s]

Extraindo embeddings:  85%|████████▍ | 731/861 [00:58<00:10, 12.44it/s]

Extraindo embeddings:  85%|████████▌ | 733/861 [00:58<00:10, 12.07it/s]

Extraindo embeddings:  85%|████████▌ | 735/861 [00:58<00:11, 10.89it/s]

Extraindo embeddings:  86%|████████▌ | 737/861 [00:58<00:10, 11.75it/s]

Extraindo embeddings:  86%|████████▌ | 739/861 [00:59<00:11, 10.51it/s]

Extraindo embeddings:  86%|████████▌ | 741/861 [00:59<00:11, 10.40it/s]

Extraindo embeddings:  86%|████████▋ | 743/861 [00:59<00:11,  9.97it/s]

Extraindo embeddings:  87%|████████▋ | 746/861 [00:59<00:10, 11.35it/s]

Extraindo embeddings:  87%|████████▋ | 748/861 [00:59<00:08, 12.71it/s]

Extraindo embeddings:  87%|████████▋ | 750/861 [00:59<00:07, 14.11it/s]

Extraindo embeddings:  87%|████████▋ | 752/861 [01:00<00:07, 14.92it/s]

Extraindo embeddings:  88%|████████▊ | 755/861 [01:00<00:06, 16.08it/s]

Extraindo embeddings:  88%|████████▊ | 758/861 [01:00<00:05, 17.87it/s]

Extraindo embeddings:  88%|████████▊ | 760/861 [01:00<00:06, 16.29it/s]

Extraindo embeddings:  89%|████████▊ | 762/861 [01:00<00:06, 14.85it/s]

Extraindo embeddings:  89%|████████▉ | 765/861 [01:00<00:05, 17.72it/s]

Extraindo embeddings:  89%|████████▉ | 767/861 [01:00<00:05, 17.32it/s]

Extraindo embeddings:  89%|████████▉ | 769/861 [01:01<00:05, 15.96it/s]

Extraindo embeddings:  90%|████████▉ | 771/861 [01:01<00:05, 16.85it/s]

Extraindo embeddings:  90%|████████▉ | 774/861 [01:01<00:05, 16.26it/s]

Extraindo embeddings:  90%|█████████ | 776/861 [01:01<00:05, 15.22it/s]

Extraindo embeddings:  90%|█████████ | 778/861 [01:01<00:05, 15.19it/s]

Extraindo embeddings:  91%|█████████ | 780/861 [01:01<00:06, 12.05it/s]

Extraindo embeddings:  91%|█████████ | 782/861 [01:02<00:06, 12.81it/s]

Extraindo embeddings:  91%|█████████ | 784/861 [01:02<00:05, 13.53it/s]

Extraindo embeddings:  91%|█████████▏| 786/861 [01:02<00:06, 11.23it/s]

Extraindo embeddings:  92%|█████████▏| 788/861 [01:02<00:07,  9.71it/s]

Extraindo embeddings:  92%|█████████▏| 790/861 [01:02<00:06, 10.97it/s]

Extraindo embeddings:  92%|█████████▏| 792/861 [01:02<00:06, 11.37it/s]

Extraindo embeddings:  92%|█████████▏| 794/861 [01:03<00:06,  9.78it/s]

Extraindo embeddings:  92%|█████████▏| 796/861 [01:03<00:06, 10.10it/s]

Extraindo embeddings:  93%|█████████▎| 798/861 [01:03<00:05, 11.12it/s]

Extraindo embeddings:  93%|█████████▎| 800/861 [01:03<00:06,  9.95it/s]

Extraindo embeddings:  93%|█████████▎| 802/861 [01:04<00:06,  8.84it/s]

Extraindo embeddings:  93%|█████████▎| 803/861 [01:04<00:07,  7.96it/s]

Extraindo embeddings:  93%|█████████▎| 804/861 [01:04<00:07,  7.97it/s]

Extraindo embeddings:  94%|█████████▎| 806/861 [01:04<00:06,  8.07it/s]

Extraindo embeddings:  94%|█████████▎| 807/861 [01:04<00:07,  7.51it/s]

Extraindo embeddings:  94%|█████████▍| 808/861 [01:04<00:06,  7.84it/s]

Extraindo embeddings:  94%|█████████▍| 810/861 [01:05<00:06,  7.85it/s]

Extraindo embeddings:  94%|█████████▍| 811/861 [01:05<00:07,  6.99it/s]

Extraindo embeddings:  94%|█████████▍| 812/861 [01:05<00:06,  7.01it/s]

Extraindo embeddings:  95%|█████████▍| 814/861 [01:05<00:05,  8.38it/s]

Extraindo embeddings:  95%|█████████▍| 815/861 [01:05<00:05,  8.03it/s]

Extraindo embeddings:  95%|█████████▍| 817/861 [01:05<00:04, 10.28it/s]

Extraindo embeddings:  95%|█████████▌| 819/861 [01:06<00:04,  8.84it/s]

Extraindo embeddings:  95%|█████████▌| 820/861 [01:06<00:04,  8.76it/s]

Extraindo embeddings:  95%|█████████▌| 821/861 [01:06<00:05,  7.70it/s]

Extraindo embeddings:  96%|█████████▌| 823/861 [01:06<00:04,  9.33it/s]

Extraindo embeddings:  96%|█████████▌| 825/861 [01:06<00:03, 10.02it/s]

Extraindo embeddings:  96%|█████████▌| 827/861 [01:07<00:03, 11.02it/s]

Extraindo embeddings:  96%|█████████▋| 829/861 [01:07<00:03,  9.25it/s]

Extraindo embeddings:  97%|█████████▋| 831/861 [01:07<00:03,  7.54it/s]

Extraindo embeddings:  97%|█████████▋| 832/861 [01:07<00:04,  7.23it/s]

Extraindo embeddings:  97%|█████████▋| 834/861 [01:08<00:03,  7.73it/s]

Extraindo embeddings:  97%|█████████▋| 835/861 [01:08<00:03,  7.99it/s]

Extraindo embeddings:  97%|█████████▋| 836/861 [01:08<00:03,  7.26it/s]

Extraindo embeddings:  97%|█████████▋| 837/861 [01:08<00:03,  6.95it/s]

Extraindo embeddings:  97%|█████████▋| 839/861 [01:08<00:02,  8.46it/s]

Extraindo embeddings:  98%|█████████▊| 841/861 [01:08<00:01, 10.29it/s]

Extraindo embeddings:  98%|█████████▊| 843/861 [01:08<00:01, 11.85it/s]

Extraindo embeddings:  98%|█████████▊| 845/861 [01:09<00:01, 13.46it/s]

Extraindo embeddings:  98%|█████████▊| 848/861 [01:09<00:00, 15.82it/s]

Extraindo embeddings:  99%|█████████▊| 850/861 [01:09<00:00, 12.22it/s]

Extraindo embeddings:  99%|█████████▉| 852/861 [01:09<00:00, 10.41it/s]

Extraindo embeddings:  99%|█████████▉| 854/861 [01:09<00:00,  9.73it/s]

Extraindo embeddings:  99%|█████████▉| 856/861 [01:10<00:00,  8.30it/s]

Extraindo embeddings: 100%|█████████▉| 857/861 [01:10<00:00,  8.02it/s]

Extraindo embeddings: 100%|█████████▉| 859/861 [01:10<00:00,  8.07it/s]

Extraindo embeddings: 100%|█████████▉| 860/861 [01:10<00:00,  8.29it/s]

Extraindo embeddings: 100%|██████████| 861/861 [01:10<00:00, 12.16it/s]

Formato da matriz de features: (116844, 1024)

# 4. Approach 1: Linear Classifier + Cleanlab (baseline)

Following the original LeNER-Br approach, we train an SGDClassifier (logistic regression) with 5-fold stratified cross-validation to obtain out-of-fold probabilities for each token.

In [10]:
# Codificar labels
label_encoder = LabelEncoder()
labels_codificados = label_encoder.fit_transform(todos_labels_ner)
num_classes = len(label_encoder.classes_)

print(f'Número de classes: {num_classes}')
print(f'Classes: {list(label_encoder.classes_)}')

Número de classes: 9
Classes: [np.str_('B-MULTA'), np.str_('B-OBRIGACAO'), np.str_('B-RECOMENDACAO'), np.str_('B-RESSARCIMENTO'), np.str_('I-MULTA'), np.str_('I-OBRIGACAO'), np.str_('I-RECOMENDACAO'), np.str_('I-RESSARCIMENTO'), np.str_('O')]

In [11]:
# Validação cruzada para obter probabilidades out-of-fold
skf = StratifiedKFold(n_splits=NUM_FOLDS_CV, shuffle=True, random_state=RANDOM_SEED)
prob_preditas_sgd = np.zeros((len(features_tokens), num_classes))

print(f'Iniciando validação cruzada de {NUM_FOLDS_CV} folds (SGDClassifier)\n')

for fold_idx, (idx_treino, idx_val) in enumerate(skf.split(features_tokens, labels_codificados)):
    print(f'  Fold {fold_idx + 1}/{NUM_FOLDS_CV}...')
    X_treino = features_tokens[idx_treino]
    X_val = features_tokens[idx_val]
    y_treino = labels_codificados[idx_treino]
    y_val = labels_codificados[idx_val]

    modelo = SGDClassifier(
        loss='log_loss',
        penalty='l2',
        alpha=0.0001,
        max_iter=1000,
        tol=1e-3,
        random_state=RANDOM_SEED,
        class_weight='balanced',
        learning_rate='optimal',
        early_stopping=True,
        n_iter_no_change=10,
        validation_fraction=0.1
    )
    modelo.fit(X_treino, y_treino)

    prob_preditas_sgd[idx_val] = modelo.predict_proba(X_val)
    acc = accuracy_score(y_val, modelo.predict(X_val))
    print(f'    Acurácia: {acc:.4f}')

print(f'\nFormato das probabilidades: {prob_preditas_sgd.shape}')

Iniciando validação cruzada de 5 folds (SGDClassifier)

  Fold 1/5...

    Acurácia: 0.8550
  Fold 2/5...

    Acurácia: 0.8510
  Fold 3/5...

    Acurácia: 0.8690
  Fold 4/5...

    Acurácia: 0.8409
  Fold 5/5...

    Acurácia: 0.8501

Formato das probabilidades: (116844, 9)

# 5. Approach 2: Fine-tuned Transformer for NER + Cleanlab

**Improvement over the original**: instead of using only a linear classifier over fixed embeddings, we fine-tune a full Transformer model for the token classification (NER) task. This yields better-calibrated and more accurate probabilities.

We use `neuralmind/bert-base-portuguese-cased` (BERTimbau Base) for fine-tuning, since it is faster and sufficient for this task. K-fold cross-validation is applied in the same way.

In [12]:
# Preparar dados no formato HuggingFace Datasets
label_list = sorted(set(todos_labels_ner))
label2id = {l: i for i, l in enumerate(label_list)}
id2label = {i: l for l, i in label2id.items()}

# Criar listas de tokens e tags por sentença
all_tokens_by_sent = []
all_tags_by_sent = []
for sent in sentencas:
    toks = [t for t, _ in sent]
    tags = [label2id[tag] for _, tag in sent]
    all_tokens_by_sent.append(toks)
    all_tags_by_sent.append(tags)

print(f'Total de sentenças: {len(all_tokens_by_sent)}')
print(f'Mapeamento label2id: {label2id}')

Total de sentenças: 861
Mapeamento label2id: {'B-MULTA': 0, 'B-OBRIGACAO': 1, 'B-RECOMENDACAO': 2, 'B-RESSARCIMENTO': 3, 'I-MULTA': 4, 'I-OBRIGACAO': 5, 'I-RECOMENDACAO': 6, 'I-RESSARCIMENTO': 7, 'O': 8}

In [13]:
ft_model_name = 'neuralmind/bert-base-portuguese-cased'
ft_tokenizer = AutoTokenizer.from_pretrained(ft_model_name)

def tokenize_and_align_labels(tokens_list, tags_list):
    """Tokeniza e alinha labels com subpalavras BERT."""
    tokenized = ft_tokenizer(
        tokens_list,
        is_split_into_words=True,
        truncation=True,
        max_length=EFFECTIVE_MAX_LENGTH,
        padding=False
    )
    
    aligned_labels = []
    word_ids = tokenized.word_ids()
    previous_word_idx = None
    for word_idx in word_ids:
        if word_idx is None:
            aligned_labels.append(-100)  # tokens especiais
        elif word_idx != previous_word_idx:
            aligned_labels.append(tags_list[word_idx])
        else:
            # Subpalavra continuação: propagar I- tag ou -100
            label = tags_list[word_idx]
            label_name = id2label[label]
            if label_name.startswith('B-'):
                aligned_labels.append(label2id['I-' + label_name[2:]])
            else:
                aligned_labels.append(label)
        previous_word_idx = word_idx
    
    tokenized['labels'] = aligned_labels
    return tokenized

In [14]:
# Cross-validation com Transformer fine-tuned
from sklearn.model_selection import KFold

# Mapear cada token plano ao seu índice de sentença para reconstruir probabilidades
token_to_sent_and_pos = []  # (sent_idx, pos_in_sent)
for sent_idx, sent in enumerate(sentencas):
    for pos in range(len(sent)):
        token_to_sent_and_pos.append((sent_idx, pos))

prob_preditas_transformer = np.zeros((len(todos_tokens), num_classes))

kf = KFold(n_splits=NUM_FOLDS_CV, shuffle=True, random_state=RANDOM_SEED)
sent_indices = np.arange(len(sentencas))

print(f'Iniciando validação cruzada de {NUM_FOLDS_CV} folds (Transformer Fine-tuned)\n')

for fold_idx, (train_sent_ids, val_sent_ids) in enumerate(kf.split(sent_indices)):
    print(f'\n=== Fold {fold_idx + 1}/{NUM_FOLDS_CV} ===')
    
    # Preparar dados de treino e validação
    train_data = {'input_ids': [], 'attention_mask': [], 'labels': []}
    val_data = {'input_ids': [], 'attention_mask': [], 'labels': []}
    val_word_ids_list = []
    
    for sid in train_sent_ids:
        enc = tokenize_and_align_labels(all_tokens_by_sent[sid], all_tags_by_sent[sid])
        train_data['input_ids'].append(enc['input_ids'])
        train_data['attention_mask'].append(enc['attention_mask'])
        train_data['labels'].append(enc['labels'])
    
    for sid in val_sent_ids:
        enc = tokenize_and_align_labels(all_tokens_by_sent[sid], all_tags_by_sent[sid])
        val_data['input_ids'].append(enc['input_ids'])
        val_data['attention_mask'].append(enc['attention_mask'])
        val_data['labels'].append(enc['labels'])
        val_word_ids_list.append(
            ft_tokenizer(
                all_tokens_by_sent[sid],
                is_split_into_words=True,
                truncation=True,
                max_length=EFFECTIVE_MAX_LENGTH
            ).word_ids()
        )
    
    train_ds = Dataset.from_dict(train_data)
    val_ds = Dataset.from_dict(val_data)
    
    # Modelo
    model_ft = AutoModelForTokenClassification.from_pretrained(
        ft_model_name,
        num_labels=num_classes,
        id2label=id2label,
        label2id=label2id
    )
    
    data_collator = DataCollatorForTokenClassification(ft_tokenizer, padding=True)
    
    training_args = TrainingArguments(
        output_dir=f'./ner_fold_{fold_idx}',
        num_train_epochs=5,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=8,
        per_device_eval_batch_size=4,
        learning_rate=3e-5,
        weight_decay=0.01,
        warmup_ratio=0.1,
        logging_steps=50,
        eval_strategy='epoch',
        save_strategy='no',
        report_to='none',
        seed=RANDOM_SEED,
        fp16=torch.cuda.is_available(),
    )
    
    trainer = Trainer(
        model=model_ft,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=data_collator,
    )
    
    trainer.train()
    
    # Predições no conjunto de validação
    predictions = trainer.predict(val_ds)
    logits = predictions.predictions  # (n_samples, seq_len, num_labels)
    
    # Extrair probabilidades por token original (não subpalavra)
    for local_idx, global_sent_idx in enumerate(val_sent_ids):
        word_ids = val_word_ids_list[local_idx]
        sent_logits = logits[local_idx]  # (seq_len, num_labels)
        sent_probs = torch.softmax(torch.tensor(sent_logits), dim=-1).numpy()
        
        # Agregar por token original (primeiro subword)
        n_orig_tokens = len(all_tokens_by_sent[global_sent_idx])
        token_probs = np.zeros((n_orig_tokens, num_classes))
        token_counts = np.zeros(n_orig_tokens)
        
        prev_word_id = None
        for subw_idx, wid in enumerate(word_ids):
            if wid is not None and subw_idx < len(sent_probs):
                if wid != prev_word_id:  # Primeiro subtoken do word
                    token_probs[wid] = sent_probs[subw_idx]
                    token_counts[wid] = 1
            prev_word_id = wid
        
        # Mapear para índice global (plano)
        # Encontrar offset global do primeiro token desta sentença
        global_offset = sum(len(sentencas[s]) for s in range(global_sent_idx))
        for pos in range(n_orig_tokens):
            flat_idx = global_offset + pos
            if flat_idx < len(prob_preditas_transformer):
                # Reordenar para match com label_encoder (que pode ter ordem diferente)
                for cls_idx, cls_name in enumerate(label_list):
                    target_idx = list(label_encoder.classes_).index(cls_name)
                    prob_preditas_transformer[flat_idx, target_idx] = token_probs[pos, cls_idx]
    
    # Limpar modelo
    del model_ft, trainer
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    elif torch.backends.mps.is_available():
        torch.mps.empty_cache()

print(f'\nFormato das probabilidades Transformer: {prob_preditas_transformer.shape}')

Iniciando validação cruzada de 5 folds (Transformer Fine-tuned)


=== Fold 1/5 ===

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== Fold 2/5 ===

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== Fold 3/5 ===

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== Fold 4/5 ===

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

=== Fold 5/5 ===

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: neuralmind/bert-base-portuguese-cased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
bert.pooler.dense.weight                   | UNEXPECTED |
cls.predictions.decoder.weight             | UNEXPECTED |
bert.pooler.dense.bias                     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Formato das probabilidades Transformer: (116844, 9)

# 6. Ensemble: Combining the Probabilities

**Further improvement**: we combine the probabilities from the two models (SGDClassifier + fine-tuned Transformer) via weighted average. This reduces false positives and increases the robustness of error detection.

In [15]:
# Peso maior para o Transformer (mais expressivo)
PESO_SGD = 0.3
PESO_TRANSFORMER = 0.7

prob_ensemble = PESO_SGD * prob_preditas_sgd + PESO_TRANSFORMER * prob_preditas_transformer

# Renormalizar para somar 1
row_sums = prob_ensemble.sum(axis=1, keepdims=True)
row_sums[row_sums == 0] = 1  # evitar divisão por zero
prob_ensemble = prob_ensemble / row_sums

print(f'Probabilidades ensemble: {prob_ensemble.shape}')
print(f'Soma de probabilidades (amostra): {prob_ensemble[:5].sum(axis=1)}')

Probabilidades ensemble: (116844, 9)
Soma de probabilidades (amostra): [1. 1. 1. 1. 1.]

# 7. Error Detection with Cleanlab

We apply Confident Learning in three configurations:
1. **SGD only** (baseline, similar to the original LeNER-Br)
2. **Transformer only**
3. **Ensemble** (most robust)

In [16]:
def detectar_erros(labels, pred_probs, nome):
    """Detecta erros de rotulagem usando Cleanlab."""
    print(f'\n--- {nome} ---')
    indices = find_label_issues(
        labels=labels,
        pred_probs=pred_probs,
        return_indices_ranked_by='self_confidence'
    )
    n = len(indices)
    pct = 100 * n / len(labels)
    print(f'Problemas encontrados: {n} ({pct:.2f}% dos tokens)')
    return indices

erros_sgd = detectar_erros(labels_codificados, prob_preditas_sgd, 'SGDClassifier (baseline)')
erros_transformer = detectar_erros(labels_codificados, prob_preditas_transformer, 'Transformer Fine-tuned')
erros_ensemble = detectar_erros(labels_codificados, prob_ensemble, 'Ensemble (SGD + Transformer)')

--- SGDClassifier (baseline) ---

Problemas encontrados: 9201 (7.87% dos tokens)

--- Transformer Fine-tuned ---

Problemas encontrados: 4325 (3.70% dos tokens)

--- Ensemble (SGD + Transformer) ---

Problemas encontrados: 4650 (3.98% dos tokens)

In [17]:
# Interseção: erros detectados por AMBOS os métodos (alta confiança)
erros_sgd_set = set(erros_sgd)
erros_transformer_set = set(erros_transformer)
erros_consenso = erros_sgd_set & erros_transformer_set

print(f'\nErros detectados pelo SGD: {len(erros_sgd_set)}')
print(f'Erros detectados pelo Transformer: {len(erros_transformer_set)}')
print(f'Erros em CONSENSO (ambos detectaram): {len(erros_consenso)}')
print(f'Erros APENAS no SGD: {len(erros_sgd_set - erros_transformer_set)}')
print(f'Erros APENAS no Transformer: {len(erros_transformer_set - erros_sgd_set)}')

Erros detectados pelo SGD: 9201
Erros detectados pelo Transformer: 4325
Erros em CONSENSO (ambos detectaram): 2350
Erros APENAS no SGD: 6851
Erros APENAS no Transformer: 1975

# 8. Analysis of the Detected Errors

We display the problems found by the ensemble with expanded context, showing the problematic token, the original label, the label suggested by the model, and the neighbouring tokens.

In [18]:
def exibir_problemas(indices_problemas, pred_probs, n_exibir=30, janela_contexto=5):
    """
    Exibe os erros de anotação detectados com contexto.
    Foca em erros que NÃO envolvem a classe 'O' (mais informativos).
    """
    problemas = []
    
    for idx in indices_problemas:
        token = todos_tokens[idx]
        label_original = todos_labels_ner[idx]
        label_codificado = labels_codificados[idx]
        
        # Label sugerido pelo modelo
        probs = pred_probs[idx]
        label_sugerido_cod = np.argmax(probs)
        label_sugerido = label_encoder.inverse_transform([label_sugerido_cod])[0]
        confianca = probs[label_sugerido_cod]
        
        # Ignorar se original e sugerido são iguais
        if label_original == label_sugerido:
            continue
        
        sent_idx = ids_sentenca[idx]
        pos_na_sent = idx - sum(len(sentencas[s]) for s in range(sent_idx))
        
        problemas.append({
            'idx_global': idx,
            'token': token,
            'label_original': label_original,
            'label_sugerido': label_sugerido,
            'confianca': confianca,
            'sent_idx': sent_idx,
            'pos_na_sent': pos_na_sent
        })
    
    # Priorizar erros que NÃO são O->entidade (mais prováveis de serem erros reais)
    erros_entidade = [p for p in problemas if p['label_original'] != 'O']
    erros_o = [p for p in problemas if p['label_original'] == 'O']
    problemas_ordenados = erros_entidade + erros_o
    
    print(f'\nTotal de discrepâncias: {len(problemas_ordenados)}')
    print(f'  - Entidade anotada incorretamente: {len(erros_entidade)}')
    print(f'  - Token O que deveria ser entidade: {len(erros_o)}')
    
    print(f'\n{"="*80}')
    print(f'DETALHES DOS PRIMEIROS {min(n_exibir, len(problemas_ordenados))} PROBLEMAS')
    print(f'{"="*80}\n')
    
    for rank, prob in enumerate(problemas_ordenados[:n_exibir], 1):
        sent = sentencas[prob['sent_idx']]
        pos = prob['pos_na_sent']
        
        # Contexto
        inicio = max(0, pos - janela_contexto)
        fim = min(len(sent), pos + janela_contexto + 1)
        
        ctx_antes = ' '.join(f'{t}({tag})' for t, tag in sent[inicio:pos])
        token_destaque = f'**{prob["token"]}**(Orig:{prob["label_original"]}|Sugerido:{prob["label_sugerido"]})'
        ctx_depois = ' '.join(f'{t}({tag})' for t, tag in sent[pos+1:fim])
        
        print(f'Problema #{rank} | Confiança: {prob["confianca"]:.4f} | Sentença #{prob["sent_idx"]}')
        print(f'  {ctx_antes} {token_destaque} {ctx_depois}')
        print()

print('\n=== ERROS DETECTADOS PELO ENSEMBLE ===')
exibir_problemas(erros_ensemble, prob_ensemble, n_exibir=30)

=== ERROS DETECTADOS PELO ENSEMBLE ===

Total de discrepâncias: 4650

  - Entidade anotada incorretamente: 2018
  - Token O que deveria ser entidade: 2632

================================================================================
DETALHES DOS PRIMEIROS 30 PROBLEMAS
================================================================================

Problema #1 | Confiança: 0.9995 | Sentença #369
  Sr.(O) Tufenis(B-MULTA) da(I-MULTA) Silva(I-MULTA) Morais,(I-MULTA) **para,**(Orig:I-MULTA|Sugerido:O) no(I-MULTA) mérito,(I-MULTA) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA)

Problema #2 | Confiança: 0.9995 | Sentença #369
  no(I-MULTA) item(I-MULTA) a(I-MULTA) e(I-MULTA) mantendo(I-MULTA) **os**(Orig:I-MULTA|Sugerido:O) demais(I-MULTA) dispositivos(I-MULTA) do(I-MULTA) Acórdão(I-MULTA) n.º(I-MULTA)

Problema #3 | Confiança: 0.9995 | Sentença #369
  no(I-MULTA) mérito,(I-MULTA) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) **excluindo**(Orig:I-MULTA|Sugerido:O) a(I-MULTA) multa(I-MULTA) imposta(I-MULTA) no(I-MULTA) item(I-MULTA)

Problema #4 | Confiança: 0.9995 | Sentença #369
  Tufenis(B-MULTA) da(I-MULTA) Silva(I-MULTA) Morais,(I-MULTA) para,(I-MULTA) **no**(Orig:I-MULTA|Sugerido:O) mérito,(I-MULTA) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) excluindo(I-MULTA)

Problema #5 | Confiança: 0.9995 | Sentença #369
  da(I-MULTA) Silva(I-MULTA) Morais,(I-MULTA) para,(I-MULTA) no(I-MULTA) **mérito,**(Orig:I-MULTA|Sugerido:O) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) excluindo(I-MULTA) a(I-MULTA)

Problema #6 | Confiança: 0.9995 | Sentença #369
  mérito,(I-MULTA) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) excluindo(I-MULTA) **a**(Orig:I-MULTA|Sugerido:O) multa(I-MULTA) imposta(I-MULTA) no(I-MULTA) item(I-MULTA) a(I-MULTA)

Problema #7 | Confiança: 0.9995 | Sentença #369
  item(I-MULTA) a(I-MULTA) e(I-MULTA) mantendo(I-MULTA) os(I-MULTA) **demais**(Orig:I-MULTA|Sugerido:O) dispositivos(I-MULTA) do(I-MULTA) Acórdão(I-MULTA) n.º(I-MULTA) 199/2016-1.ª(I-MULTA)

Problema #8 | Confiança: 0.9992 | Sentença #506
  do(O) pedido(O) de(O) reexame(O) interposto.(O) **Como**(Orig:B-RECOMENDACAO|Sugerido:O) também(I-RECOMENDACAO) para(I-RECOMENDACAO) que(I-RECOMENDACAO) o(I-RECOMENDACAO) novo(I-RECOMENDACAO)

Problema #9 | Confiança: 0.9984 | Sentença #571
  valor(I-MULTA) de(I-MULTA) R$(I-MULTA) 505,66,(I-MULTA) pela(I-MULTA) **intempestividade**(Orig:I-MULTA|Sugerido:O) da(I-MULTA) diligência.(I-MULTA)

Problema #10 | Confiança: 0.9985 | Sentença #491
  Sr.(O) Paulo(O) Emídio(O) de(O) Medeiros;(O) **b)**(Orig:B-OBRIGACAO|Sugerido:O) Pela(I-OBRIGACAO) fixação(I-OBRIGACAO) de(I-OBRIGACAO) prazo(I-OBRIGACAO) de(I-OBRIGACAO)

Problema #11 | Confiança: 0.9995 | Sentença #369
  imposta(I-MULTA) no(I-MULTA) item(I-MULTA) a(I-MULTA) e(I-MULTA) **mantendo**(Orig:I-MULTA|Sugerido:O) os(I-MULTA) demais(I-MULTA) dispositivos(I-MULTA) do(I-MULTA) Acórdão(I-MULTA)

Problema #12 | Confiança: 0.9995 | Sentença #369
  multa(I-MULTA) imposta(I-MULTA) no(I-MULTA) item(I-MULTA) a(I-MULTA) **e**(Orig:I-MULTA|Sugerido:O) mantendo(I-MULTA) os(I-MULTA) demais(I-MULTA) dispositivos(I-MULTA) do(I-MULTA)

Problema #13 | Confiança: 0.9992 | Sentença #369
  a(I-MULTA) multa(I-MULTA) imposta(I-MULTA) no(I-MULTA) item(I-MULTA) **a**(Orig:I-MULTA|Sugerido:O) e(I-MULTA) mantendo(I-MULTA) os(I-MULTA) demais(I-MULTA) dispositivos(I-MULTA)

Problema #14 | Confiança: 0.9995 | Sentença #369
  para,(I-MULTA) no(I-MULTA) mérito,(I-MULTA) DAR-LHE(I-MULTA) PROVIMENTO(I-MULTA) **PARCIAL,**(Orig:I-MULTA|Sugerido:O) excluindo(I-MULTA) a(I-MULTA) multa(I-MULTA) imposta(I-MULTA) no(I-MULTA)

Problema #15 | Confiança: 0.9983 | Sentença #638
  admissional(O) em(O) epígrafe;(O) b)(O) pela(O) **cientificação**(Orig:B-RECOMENDACAO|Sugerido:O) imediata(I-RECOMENDACAO) da(I-RECOMENDACAO) Secretaria(I-RECOMENDACAO) de(I-RECOMENDACAO) Controle(I-RECOMENDACAO)

Problema #16 | Confiança: 0.9960 | Sentença #369
  de(O) reconsideração(O) interposto(O) pelo(O) Sr.(O) **Tufenis**(Orig:B-MULTA|Sugerido:O) da(I-MULTA) Silva(I-MULTA) Morais,(I-MULTA) para,(I-MULTA) no(I-MULTA)

Problema #17 | Confiança: 0.9990 | Sentença #781
  Ministério(I-RESSARCIMENTO) Público(I-RESSARCIMENTO) estadual(I-RESSARCIMENTO) para(I-RESSARCIMENTO) ciência(I-RESSARCIMENTO) **do**(Orig:I-RESSARCIMENTO|Sugerido:O) decisum.(I-RESSARCIMENTO)

Problema #18 | Confiança: 0.9890 | Sentença #781
  cópia(I-RESSARCIMENTO) ao(I-RESSARCIMENTO) Ministério(I-RESSARCIMENTO) Público(I-RESSARCIMENTO) estadual(I-RESSARCIMENTO) **para**(Orig:I-RESSARCIMENTO|Sugerido:O) ciência(I-RESSARCIMENTO) do(I-RESSARCIMENTO) decisum.(I-RESSARCIMENTO)

Problema #19 | Confiança: 0.8874 | Sentença #287
  464/2012.(O) Também,(O) pela(O) expedição(O) de(O) **RECOMENDAÇÃO**(Orig:B-RECOMENDACAO|Sugerido:O) ao(I-RECOMENDACAO) Consórcio(I-RECOMENDACAO) Público(I-RECOMENDACAO) Regional(I-RECOMENDACAO) de(I-RECOMENDACAO)

Problema #20 | Confiança: 0.9979 | Sentença #561
  observações(I-OBRIGACAO) presentes(I-OBRIGACAO) nas(I-OBRIGACAO) manifestações(I-OBRIGACAO) do(I-OBRIGACAO) **Corpo**(Orig:I-OBRIGACAO|Sugerido:O) Técnico(I-OBRIGACAO) e(I-OBRIGACAO) do(I-OBRIGACAO) Parquet(I-OBRIGACAO) Especial,(I-OBRIGACAO)

Problema #21 | Confiança: 0.9991 | Sentença #506
  de(O) reexame(O) interposto.(O) Como(B-RECOMENDACAO) também(I-RECOMENDACAO) **para**(Orig:I-RECOMENDACAO|Sugerido:O) que(I-RECOMENDACAO) o(I-RECOMENDACAO) novo(I-RECOMENDACAO) parecer(I-RECOMENDACAO) prévio(I-RECOMENDACAO)

Problema #22 | Confiança: 0.9945 | Sentença #781
  Público(I-RESSARCIMENTO) estadual(I-RESSARCIMENTO) para(I-RESSARCIMENTO) ciência(I-RESSARCIMENTO) do(I-RESSARCIMENTO) **decisum.**(Orig:I-RESSARCIMENTO|Sugerido:O)

Problema #23 | Confiança: 0.9994 | Sentença #369
  Silva(I-MULTA) Morais,(I-MULTA) para,(I-MULTA) no(I-MULTA) mérito,(I-MULTA) **DAR-LHE**(Orig:I-MULTA|Sugerido:O) PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) excluindo(I-MULTA) a(I-MULTA) multa(I-MULTA)

Problema #24 | Confiança: 0.9710 | Sentença #781
  da(I-RESSARCIMENTO) Lei(I-RESSARCIMENTO) Complementar(I-RESSARCIMENTO) nº(I-RESSARCIMENTO) 121/94;c)(I-RESSARCIMENTO) **Após**(Orig:I-RESSARCIMENTO|Sugerido:O) o(I-RESSARCIMENTO) trânsito(I-RESSARCIMENTO) em(I-RESSARCIMENTO) julgado,(I-RESSARCIMENTO) remetam-se(I-RESSARCIMENTO)

Problema #25 | Confiança: 0.8283 | Sentença #506
  pedido(O) de(O) reexame(O) interposto.(O) Como(B-RECOMENDACAO) **também**(Orig:I-RECOMENDACAO|Sugerido:O) para(I-RECOMENDACAO) que(I-RECOMENDACAO) o(I-RECOMENDACAO) novo(I-RECOMENDACAO) parecer(I-RECOMENDACAO)

Problema #26 | Confiança: 0.9994 | Sentença #369
  PROVIMENTO(I-MULTA) PARCIAL,(I-MULTA) excluindo(I-MULTA) a(I-MULTA) multa(I-MULTA) **imposta**(Orig:I-MULTA|Sugerido:O) no(I-MULTA) item(I-MULTA) a(I-MULTA) e(I-MULTA) mantendo(I-MULTA)

Problema #27 | Confiança: 0.9983 | Sentença #781
  juros(I-RESSARCIMENTO) e(I-RESSARCIMENTO) atualização(I-RESSARCIMENTO) monetária.(I-RESSARCIMENTO) d)(I-RESSARCIMENTO) **Encaminhe-se**(Orig:I-RESSARCIMENTO|Sugerido:O) cópia(I-RESSARCIMENTO) ao(I-RESSARCIMENTO) Ministério(I-RESSARCIMENTO) Público(I-RESSARCIMENTO) estadual(I-RESSARCIMENTO)

Problema #28 | Confiança: 0.7260 | Sentença #506
  interposto.(O) Como(B-RECOMENDACAO) também(I-RECOMENDACAO) para(I-RECOMENDACAO) que(I-RECOMENDACAO) **o**(Orig:I-RECOMENDACAO|Sugerido:O) novo(I-RECOMENDACAO) parecer(I-RECOMENDACAO) prévio(I-RECOMENDACAO) a(I-RECOMENDACAO) ser(I-RECOMENDACAO)

Problema #29 | Confiança: 0.9987 | Sentença #491
  cargos(I-OBRIGACAO) acumulados.(I-OBRIGACAO) c)(I-OBRIGACAO) Por(I-OBRIGACAO) derradeiro,(I-OBRIGACAO) **ainda,**(Orig:I-OBRIGACAO|Sugerido:O) na(I-OBRIGACAO) hipótese(I-OBRIGACAO) de(I-OBRIGACAO) descumprimento(I-OBRIGACAO) deste(I-OBRIGACAO)

Problema #30 | Confiança: 0.9981 | Sentença #491
  Município,(I-OBRIGACAO) excluindo(I-OBRIGACAO) os(I-OBRIGACAO) cargos(I-OBRIGACAO) acumulados.(I-OBRIGACAO) **c)**(Orig:I-OBRIGACAO|Sugerido:O) Por(I-OBRIGACAO) derradeiro,(I-OBRIGACAO) ainda,(I-OBRIGACAO) na(I-OBRIGACAO) hipótese(I-OBRIGACAO)

# 9. Statistical Summary of the Errors

We analyse the distribution of the error types found.

In [19]:
def resumo_erros(indices_problemas, pred_probs, nome):
    """Gera um resumo da distribuição de erros."""
    transicoes = Counter()
    
    for idx in indices_problemas:
        label_orig = todos_labels_ner[idx]
        label_sug = label_encoder.inverse_transform([np.argmax(pred_probs[idx])])[0]
        if label_orig != label_sug:
            transicoes[(label_orig, label_sug)] += 1
    
    print(f'\n=== Matriz de Confusão de Erros ({nome}) ===')
    print(f'{"Original":>20s} -> {"Sugerido":<20s} | Quantidade')
    print('-' * 60)
    for (orig, sug), count in transicoes.most_common(20):
        print(f'{orig:>20s} -> {sug:<20s} | {count}')

resumo_erros(erros_ensemble, prob_ensemble, 'Ensemble')

=== Matriz de Confusão de Erros (Ensemble) ===
            Original -> Sugerido             | Quantidade
------------------------------------------------------------
                   O -> I-OBRIGACAO          | 640
                   O -> I-RECOMENDACAO       | 547
                   O -> B-OBRIGACAO          | 417
                   O -> B-RECOMENDACAO       | 412
                   O -> I-MULTA              | 387
         I-OBRIGACAO -> B-RECOMENDACAO       | 241
                   O -> I-RESSARCIMENTO      | 229
         I-OBRIGACAO -> B-OBRIGACAO          | 219
         I-OBRIGACAO -> O                    | 213
             I-MULTA -> B-OBRIGACAO          | 192
             I-MULTA -> B-RECOMENDACAO       | 164
     I-RESSARCIMENTO -> O                    | 132
             I-MULTA -> O                    | 108
             I-MULTA -> I-RESSARCIMENTO      | 105
      I-RECOMENDACAO -> O                    | 77
             I-MULTA -> I-OBRIGACAO          | 72
      I-RECOMENDACAO -> I-OBRIGACAO          | 58
     I-RESSARCIMENTO -> I-MULTA              | 54
         I-OBRIGACAO -> I-RESSARCIMENTO      | 51
      I-RECOMENDACAO -> B-OBRIGACAO          | 45

In [20]:
# Exportar erros para análise manual
erros_para_csv = []
for idx in erros_ensemble:
    label_orig = todos_labels_ner[idx]
    probs = prob_ensemble[idx]
    label_sug = label_encoder.inverse_transform([np.argmax(probs)])[0]
    if label_orig != label_sug:
        sent_idx = ids_sentenca[idx]
        pos = idx - sum(len(sentencas[s]) for s in range(sent_idx))
        sent = sentencas[sent_idx]
        ctx_start = max(0, pos - 3)
        ctx_end = min(len(sent), pos + 4)
        contexto = ' '.join(t for t, _ in sent[ctx_start:ctx_end])
        
        erros_para_csv.append({
            'token': todos_tokens[idx],
            'label_original': label_orig,
            'label_sugerido': label_sug,
            'confianca': float(np.max(probs)),
            'sentenca_idx': sent_idx,
            'contexto': contexto
        })

df_erros = pd.DataFrame(erros_para_csv)
df_erros.to_csv('dataset/errors/erros_anotacao_decicontas.csv', index=False)
print(f'Exportados {len(df_erros)} erros para erros_anotacao_decicontas.csv')
df_erros.head(10)

Exportados 4650 erros para dataset/errors/erros_anotacao_decicontas.csv

,token,label_original,label_sugerido,confianca,sentenca_idx,contexto
0,"para,",I-MULTA,O,0.999521,369,"da Silva Morais, para, no mérito, DAR-LHE"
1,os,I-MULTA,O,0.999497,369,a e mantendo os demais dispositivos do
2,excluindo,I-MULTA,O,0.999498,369,"DAR-LHE PROVIMENTO PARCIAL, excluindo a multa ..."
3,no,I-MULTA,O,0.999462,369,"Silva Morais, para, no mérito, DAR-LHE PROVIMENTO"
4,"mérito,",I-MULTA,O,0.999505,369,"Morais, para, no mérito, DAR-LHE PROVIMENTO PA..."
5,a,I-MULTA,O,0.999502,369,"PROVIMENTO PARCIAL, excluindo a multa imposta no"
6,demais,I-MULTA,O,0.999490,369,e mantendo os demais dispositivos do Acórdão
7,Como,B-RECOMENDACAO,O,0.999150,506,de reexame interposto. Como também para que
8,intempestividade,I-MULTA,O,0.998418,571,"R$ 505,66, pela intempestividade da diligência."
9,b),B-OBRIGACAO,O,0.998497,491,Emídio de Medeiros; b) Pela fixação de

# 10. Conclusion

In this notebook we applied **Confident Learning** techniques (via Cleanlab) to detect annotation errors in the TCE/RN `decicontas.br` dataset.

### Improvements over the original approach (LeNER-Br):

1. **Format adaptation**: automatic conversion of Label Studio annotations (spans with offsets) to token-level BIO format.
2. **Fine-tuned Transformer**: besides the linear classifier over BERT embeddings (baseline), we fine-tuned a full BERTimbau model for token classification, producing more accurate probabilities.
3. **Model ensemble**: weighted combination of the probabilities from two independent models for greater robustness.
4. **Multi-method analysis**: comparison of errors detected by each method and identification of consensus cases.
5. **Structured export**: the errors are exported to CSV to simplify manual review.

### Next steps:
- Manual review of the highest-confidence detected errors.
- Semi-automatic retagging using the ensemble's suggestions as a starting point.
- Use of LLMs (GPT-4, etc.) as additional verifiers for ambiguous cases, leveraging the infrastructure already in place in the project.